apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-gateway-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-gateway-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "cluster-gateway-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cluster-gateway-manager.labels" . | nindent 8 }}
    spec:
      serviceAccount: cluster-gateway-manager
      automountServiceAccountToken: true
      containers:
        - name: manager
          image: {{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}
          imagePullPolicy: Always
          args:
            {{- if gt (int .Values.replicas) 1 }}
            - --leader-elect=true
            {{- end }}
            {{- if .Values.kubeconfigSecretName }}
            - --multicluster-kubeconfig=/var/run/secrets/ocm/auth/kubeconfig
            - --multicluster-kubeconfig-secret-name={{ .Values.kubeconfigSecretName }}
            {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NAMESPACE
              value: {{ include "cluster-gateway-manager.namespace" . }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          volumeMounts:
          {{- if .Values.kubeconfigSecretName }}
            - mountPath: /var/run/secrets/ocm/auth
              name: ocm-auth
          {{- end }}
      volumes:
        {{- if .Values.kubeconfigSecretName }}
        - name: ocm-auth
          secret:
            defaultMode: 420
            secretName: {{ .Values.kubeconfigSecretName }}
        {{- end }}
