project:
  name: cluster-proxy-manager
  shortName: cluster-proxy-manager
  url: https://github.com/kluster-manager/cluster-proxy
  description: Installs cluster-proxy in managed clusters
  app: a cluster-proxy-manager
repository:
  url: https://charts.appscode.com/stable
  name: appscode
chart:
  name: cluster-proxy-manager
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.21+
release:
  name: cluster-proxy-manager
  namespace: open-cluster-management-addon
