# Image registry
registry: ghcr.io/kluster-manager

# Image of the cluster-gateway instances
image: cluster-proxy

# Image tag
tag: ""

# Number of replicas
replicas: 1

securityContext: # +doc-gen:break
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault

proxyServerImage: ghcr.io/kluster-manager/cluster-proxy
proxyAgentImage: ghcr.io/kluster-manager/cluster-proxy

proxyServer:
  entrypointLoadBalancer: false
  entrypointAddress: ""
  port: 8091

# required for multicluster controlplane
kubeconfigSecretName: ""

kubectl:
  image: ghcr.io/appscode/kubectl-nonroot:1.31
