{{- if .Values.placement.create }}

apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace: {{ include "cluster-auth-manager.namespace" . }}
spec:
  clusterSet: global

{{- end }}
