{{- if .Values.placement.create }}

apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ .Values.placement.name }}
  namespace: {{ include "cluster-auth-manager.namespace" . }}
spec:
  clusterSets:
    - global

{{- end }}
