{{- if .Values.kubeconfigSecretName }}

apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: cluster-gateway
spec:
  addOnMeta:
    displayName: {{ .Chart.Name }}
    description: {{ .Chart.Description }}
  installStrategy:
    type: Manual

{{- end }}
