apiVersion: fluxcd.open-cluster-management.io/v1alpha1
kind: FluxCDConfig
metadata:
  labels:
    app.kubernetes.io/name: fluxcdconfig
    app.kubernetes.io/instance: fluxcdconfig
    app.kubernetes.io/part-of: api
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: api
  name: fluxcd-config
  namespace: open-cluster-management-fluxcd
spec:
  installCRDs: true
  helmController:
    create: true
  sourceController:
    create: true
  imageReflectionController:
    create: false
  imageAutomationController:
    create: false
  kustomizeController:
    create: false
  notificationController:
    create: false
