{{ $cmNS := default .Release.Namespace $.Values.configMap.namespace }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "multicluster-ingress-reader.fullname" . }}:cm-creator
  namespace: {{ $cmNS }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "multicluster-ingress-reader.fullname" . }}:cm-creator
  namespace: {{ $cmNS }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "multicluster-ingress-reader.fullname" . }}:cm-creator
subjects:
  - kind: ServiceAccount
    name: {{ include "multicluster-ingress-reader.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
