apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "multicluster-ingress-reader.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
      - patch
