apiVersion: v2
name: fluxcd-manager
description: Installs FluxCD in managed clusters
type: application
version: v2024.2.25
appVersion: "v0.0.2"
home: https://open-cluster-management.io
sources:
- https://github.com/kluster-manager/installer
maintainers:
- name: appscode
  email: support@appscode.com
