image: ghcr.io/kluster-manager/fluxcd-addon
tag:

kubeconfigSecretName: ""

kubectl:
  image: ghcr.io/appscode/kubectl:1.23

fluxcdConfig:
  installCRDs: true
  helmController:
    create: true
  sourceController:
    create: true
  imageReflectionController:
    create: false
  imageAutomationController:
    create: false
  kustomizeController:
    create: false
  notificationController:
    create: false
