nameOverride: ""
fullnameOverride: ""

image: ghcr.io/kluster-manager/fluxcd-addon
tag:

kubeconfigSecretName: ""
addonManagerNamespace: open-cluster-management-fluxcd

placement:
  create: true
  name: global

kubectl:
  image: ghcr.io/appscode/kubectl-nonroot:1.25

fluxcdConfig:
  installCRDs: true
  helmController:
    create: true
  sourceController:
    create: true
  imageReflectionController:
    create: false
  imageAutomationController:
    create: false
  kustomizeController:
    create: false
  notificationController:
    create: false
