nameOverride: ""
fullnameOverride: ""

image: ghcr.io/kluster-manager/fluxcd-addon
tag:

kubeconfigSecretName: ""
addonManagerNamespace: open-cluster-management-fluxcd

placement:
  create: true
  name: global

kubectl:
  image: ghcr.io/appscode/kubectl-nonroot:1.31

fluxcdConfig:
  installCRDs: true
  cli:
    image: ghcr.io/appscode/flux-cli
  helmController:
    create: true
    image: ghcr.io/fluxcd/helm-controller
  imageAutomationController:
    create: false
    image: ghcr.io/fluxcd/image-automation-controller
  imageReflectionController:
    create: false
    image: ghcr.io/fluxcd/image-reflector-controller
  kustomizeController:
    create: true
    image: ghcr.io/fluxcd/kustomize-controller
  notificationController:
    create: true
    image: ghcr.io/fluxcd/notification-controller
  sourceController:
    create: true
    image: ghcr.io/fluxcd/source-controller
