apiVersion: v2
name: cluster-manager-spoke
description: A Helm chart to join a spoke cluster to Open Cluster Manager Hub
type: application
version: 0.1.0
appVersion: "v0.12.0"
home: https://open-cluster-management.io
sources:
- https://github.com/kluster-manager/installer
maintainers:
- name: appscode
  email: support@appscode.com
