clusterMetadata:
  name: TBD
  store:
    clusterClaim:
      name: cluster.ace.info
      # name: ""
      # namespace: ""

secret:
  name: ace-cluster-info
  namespace: kubeops

hub:
  apiServer: ""
  caData: ""
  token: ""
  kubeConfig: ""

registry: quay.io/open-cluster-management

bundleVersion:
  registrationImageVersion: ""
  placementImageVersion: ""
  workImageVersion: ""
  operatorImageVersion: ""
  clusteradmImageVersion: "v0.9.0"

managedKubeconfig: ''

registrationFeatures: []

workFeatures: []
