properties:
  bundleVersion:
    properties:
      clusteradmImageVersion:
        type: string
      operatorImageVersion:
        type: string
      placementImageVersion:
        type: string
      registrationImageVersion:
        type: string
      workImageVersion:
        type: string
    type: object
  clusterMetadata:
    properties:
      name:
        type: string
      store:
        properties:
          clusterClaim:
            properties:
              name:
                default: ''
                type: string
            type: object
            x-kubernetes-map-type: atomic
          secret:
            properties:
              name:
                type: string
              namespace:
                type: string
            type: object
        required:
        - clusterClaim
        - secret
        type: object
    required:
    - name
    - store
    type: object
  hub:
    properties:
      apiServer:
        type: string
      caData:
        type: string
      kubeConfig:
        type: string
      token:
        type: string
    type: object
  managedKubeconfig:
    type: string
  registrationFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
  registry:
    type: string
  workFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
required:
- clusterMetadata
type: object
