properties:
  bundleVersion:
    properties:
      clusteradmImageVersion:
        type: string
      operatorImageVersion:
        type: string
      placementImageVersion:
        type: string
      registrationImageVersion:
        type: string
      workImageVersion:
        type: string
    type: object
  clusterMetadata:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  hub:
    properties:
      apiServer:
        type: string
      caData:
        type: string
      kubeConfig:
        type: string
      token:
        type: string
    type: object
  managedKubeconfig:
    type: string
  registrationFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
  registry:
    type: string
  secret:
    properties:
      apiVersion:
        type: string
      fieldPath:
        type: string
      kind:
        type: string
      name:
        type: string
      namespace:
        type: string
      resourceVersion:
        type: string
      uid:
        type: string
    type: object
    x-kubernetes-map-type: atomic
  workFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
required:
- clusterMetadata
- secret
type: object
