clusterMetadata:
  name: TBD
  store:
    clusterClaim:
      name: cluster.ace.info
    secret:
      # name: ""
      # namespace: ""
      name: ace-cluster-info
      namespace: kubeops

hub:
  apiServer: ""
  caData: ""
  token: ""
  kubeConfig: ""

registry: quay.io/open-cluster-management

clusteradm:
  image: ghcr.io/kluster-manager/clusteradm

bundleVersion:
  registrationImageVersion: ""
  placementImageVersion: ""
  workImageVersion: ""
  operatorImageVersion: ""
  clusteradmImageVersion: "v0.9.0"

managedKubeconfig: ''

registrationFeatures: []

workFeatures: []
