apiVersion: v1
description: Cluster Auth Manager
name: cluster-auth-manager
version: v2024.11.18
appVersion: v0.2.0
home: https://github.com/kluster-manager/cluster-auth
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kluster-manager/cluster-auth
maintainers:
- name: appscode
  email: support@appscode.com
