nameOverride: ""
fullnameOverride: ""

# Docker registry fqdn used to pull license-proxyserver docker images
registryFQDN: ghcr.io

image: ghcr.io/kluster-manager/cluster-auth
tag: ""
imagePullPolicy: Always

securityContext: # +doc-gen:break
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault

kubeconfigSecretName: ""
addonManagerNamespace: open-cluster-management-cluster-auth

placement:
  create: true
  name: global

kubectl:
  image: ghcr.io/appscode/kubectl-nonroot:1.31
