nameOverride: ""
fullnameOverride: ""

# Docker registry fqdn used to pull license-proxyserver docker images
registryFQDN: ghcr.io

image: ghcr.io/kluster-manager/cluster-auth
tag: ""
imagePullPolicy: Always

kubeconfigSecretName: ""

kubectl:
  image: ghcr.io/appscode/kubectl:1.25
