properties:
  addonManagerNamespace:
    type: string
  fullnameOverride:
    type: string
  image:
    type: string
  imagePullPolicy:
    type: string
  kubeconfigSecretName:
    type: string
  kubectl:
    properties:
      image:
        type: string
    required:
    - image
    type: object
  nameOverride:
    type: string
  placement:
    properties:
      create:
        type: boolean
      name:
        type: string
    required:
    - create
    - name
    type: object
  registryFQDN:
    type: string
  tag:
    type: string
required:
- image
- imagePullPolicy
- kubectl
- placement
- registryFQDN
type: object
