properties:
  fullnameOverride:
    type: string
  image:
    type: string
  imagePullPolicy:
    type: string
  kubeconfigSecretName:
    type: string
  kubectl:
    properties:
      image:
        type: string
    required:
    - image
    type: object
  nameOverride:
    type: string
  registryFQDN:
    type: string
  tag:
    type: string
required:
- image
- imagePullPolicy
- kubectl
- registryFQDN
type: object
