{{- if ne .Values.hubDeployMode "AddOnTemplate" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: managed-serviceaccount-addon-manager
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      open-cluster-management.io/addon: managed-serviceaccount
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: managed-serviceaccount
    spec:
      {{- if .Values.kubeconfigSecretName }}
      automountServiceAccountToken: false
      {{- else }}
      serviceAccount: managed-serviceaccount
      automountServiceAccountToken: true
      {{- end }}
      containers:
        - name: manager
          image: {{ .Values.image }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            {{- if gt (int .Values.replicas) 1 }}
            - --leader-elect=true
            {{- end }}
            - --agent-image-name={{ .Values.image }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
            - --agent-install-all={{ .Values.agentInstallAll }}
            {{- if .Values.featureGates }}
            - --feature-gates=EphemeralIdentity={{ .Values.featureGates.ephemeralIdentity | default false}}
            {{- end}}
            {{- if .Values.agentImagePullSecret }}
            - --agent-image-pull-secret={{ .Values.agentImagePullSecret }}
            {{- end}}
            {{- if .Values.kubeconfigSecretName }}
            - --kubeconfig=/var/run/secrets/ocm/auth/kubeconfig
            {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
          {{- if .Values.kubeconfigSecretName }}
            - mountPath: /var/run/secrets/ocm/auth
              name: ocm-auth
          {{- end }}
      volumes:
        {{- if .Values.kubeconfigSecretName }}
        - name: ocm-auth
          secret:
            defaultMode: 420
            secretName: {{ .Values.kubeconfigSecretName }}
        {{- end }}
{{- end }}
