project:
  name: Spoke Cluster Addons
  shortName: Spoke Cluster Addons
  url: https://github.com/kluster-manager/installer
  description: Spoke Cluster Addons
  app: a Spoke Cluster Addons
repository:
  url: https://charts.appscode.com/stable
  name: appscode
chart:
  name: spoke-cluster-addons
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.21+
release:
  name: spoke-cluster-addons
  namespace: c1
