apiVersion: v1
description: Hub Cluster Robot
name: hub-cluster-robot
version: v2024.8.9
appVersion: v0.0.1
home: https://github.com/kluster-manager/cluster-auth
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kluster-manager/cluster-auth
maintainers:
- name: appscode
  email: support@appscode.com
