apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:hub-cluster-robot:cluster-auth
rules:
  - apiGroups: [""]
    resources: ["secrets", "serviceaccounts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "authentication.k8s.appscode.com" ]
    resources: [ "*" ]
    verbs: [ "*" ]
