apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: open-cluster-management:hub-cluster-robot:cluster-auth
  namespace: open-cluster-management-cluster-auth
rules:
  - apiGroups: [""]
    resources: ["secrets", "serviceaccounts"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:hub-cluster-robot:cluster-auth
rules:
  - apiGroups: [ "authentication.k8s.appscode.com" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "cluster.open-cluster-management.io" ]
    resources: [ "managedclusters", "managedclustersets" ]
    verbs: [ "*" ]
