apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:hub-cluster-robot:cluster-auth
  namespace: open-cluster-management-cluster-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:hub-cluster-robot:cluster-auth
subjects:
  - kind: ServiceAccount
    name: hub-cluster-robot
    namespace: {{ include "hub-cluster-robot.namespace" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:hub-cluster-robot:cluster-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:hub-cluster-robot:cluster-auth
subjects:
  - kind: ServiceAccount
    name: hub-cluster-robot
    namespace: {{ include "hub-cluster-robot.namespace" . }}
