apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: hub-cluster-robot
  namespace: {{ include "hub-cluster-robot.namespace" . }}
  annotations:
    kubernetes.io/service-account.name: hub-cluster-robot
