project:
  name: cluster-gateway-manager
  shortName: cluster-gateway-manager
  url: https://github.com/kluster-manager/cluster-gateway
  description: Installs cluster-gateway-manager in managed clusters
  app: a cluster-gateway-manager
repository:
  url: https://charts.appscode.com/stable
  name: appscode
chart:
  name: cluster-gateway-manager
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.21+
release:
  name: cluster-gateway-manager
  namespace: open-cluster-management-cluster-gateway
