nameOverride: ""
fullnameOverride: ""

# Image of the cluster-gateway instances
image: ghcr.io/kluster-manager/cluster-gateway-manager
tag: ""

securityContext: # +doc-gen:break
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault

clusterGateway:
  image: ghcr.io/kluster-manager/cluster-gateway

# Number of replicas
replicas: 1

manualSecretManagement: false

clusterProxy:
  enabled: true
  proxyServerHost: "proxy-entrypoint.open-cluster-management-addon.svc"
  proxyServerPort: 8090
  credentials:
    namespace: open-cluster-management-addon
    proxyClientCASecretName: proxy-server-ca
    proxyClientSecretName: proxy-client

kubeconfigSecretName: ""
addonManagerNamespace: open-cluster-management-cluster-gateway

placement:
  create: true
  name: global

kubectl:
  image: ghcr.io/appscode/kubectl-nonroot:1.31

clusterAuthNamespace: open-cluster-management-cluster-auth
