# Image of the cluster-gateway instances
image: oamdev/cluster-gateway-manager

tag:

clusterGateway:
  image: oamdev/cluster-gateway
  installNamespace: vela-system
  secretNamespace: open-cluster-management-credentials
# Number of replicas
replicas: 1

manualSecretManagement: true
konnectivityEgress: false