apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluxcd-addon-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluxcd-addon-manager
subjects:
  - kind: ServiceAccount
    name: fluxcd-addon-manager
    namespace: fluxcd-addon
