kind: Deployment
apiVersion: apps/v1
metadata:
  name: fluxcd-addon-manager
  namespace: fluxcd-addon
  labels:
    app: fluxcd-addon-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluxcd-addon-manager
  template:
    metadata:
      labels:
        app: fluxcd-addon-manager
    spec:
      serviceAccountName: fluxcd-addon-manager
      containers:
        - name: fluxcd-addon-manager
          image: ghcr.io/kluster-manager/fluxcd-addon:latest
          imagePullPolicy: IfNotPresent
