{{- if and (ne .Values.hubDeployMode "AddOnTemplate") .Values.kubeconfigSecretName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: managed-serviceaccount
  namespace: {{ .Release.Namespace }}
{{- end }}
