# Grant cluster-gateway permission to all users' service accounts
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-gateway-permission
rules:
  - apiGroups:
      - cluster.core.oam.dev
    resources:
      - clustergateways/health
      - clustergateways/proxy
    verbs:
      - "*"
