# Grant cluster-gateway permission to all users' service accounts
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:cluster-gateway:proxy
rules:
  - apiGroups:
      - gateway.open-cluster-management.io
    resources:
      - clustergateways
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - gateway.open-cluster-management.io
    resources:
      - clustergateways/health
    verbs: ["get"]
  - apiGroups:
      - gateway.open-cluster-management.io
    resources:
      - clustergateways/proxy
    verbs: ["*"]
