kind: Deployment
apiVersion: apps/v1
metadata:
  name: fluxcd-manager
  namespace: {{ ternary "open-cluster-management-fluxcd" .Release.Namespace (empty .Values.kubeconfigSecretName) }}
  labels:
    app: fluxcd-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluxcd-manager
  template:
    metadata:
      labels:
        app: fluxcd-manager
    spec:
      {{- if .Values.kubeconfigSecretName }}
      automountServiceAccountToken: false
      {{- else }}
      serviceAccount: fluxcd-manager
      automountServiceAccountToken: true
      {{- end }}
      containers:
        - name: manager
          image: {{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          args:
            - manager
            {{- if .Values.kubeconfigSecretName }}
            - --kubeconfig=/var/run/secrets/ocm/auth/kubeconfig
            {{- end }}
          volumeMounts:
          {{- if .Values.kubeconfigSecretName }}
            - mountPath: /var/run/secrets/ocm/auth
              name: ocm-auth
          {{- end }}
      volumes:
        {{- if .Values.kubeconfigSecretName }}
        - name: ocm-auth
          secret:
            defaultMode: 420
            secretName: {{ .Values.kubeconfigSecretName }}
        {{- end }}
