kind: Deployment
apiVersion: apps/v1
metadata:
  name: fluxcd-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluxcd-manager.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fluxcd-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fluxcd-manager.labels" . | nindent 8 }}
    spec:
      {{- if .Values.kubeconfigSecretName }}
      automountServiceAccountToken: false
      {{- else }}
      serviceAccount: fluxcd-manager
      automountServiceAccountToken: true
      {{- end }}
      containers:
        - name: manager
          image: {{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          args:
            - manager
            {{- if .Values.kubeconfigSecretName }}
            - --kubeconfig=/var/run/secrets/ocm/auth/kubeconfig
            {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NAMESPACE
              value: {{ include "fluxcd-manager.namespace" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-dir
          {{- if .Values.kubeconfigSecretName }}
            - mountPath: /var/run/secrets/ocm/auth
              name: ocm-auth
          {{- end }}
      volumes:
        - name: tmp-dir
          emptyDir: {}
        {{- if .Values.kubeconfigSecretName }}
        - name: ocm-auth
          secret:
            defaultMode: 420
            secretName: {{ .Values.kubeconfigSecretName }}
        {{- end }}
