apiVersion: config.gateway.open-cluster-management.io/v1alpha1
kind: ClusterGatewayConfiguration
metadata:
  name: cluster-gateway
spec:
  image: {{ .Values.clusterGateway.image }}:{{ .Values.tag | default .Chart.AppVersion }}
  secretManagement:
  {{ if .Values.manualSecretManagement }}
    type: Manual
  {{ else }}
    type: ManagedServiceAccount
    managedServiceAccount:
      name: cluster-gateway
  {{ end }}
  egress:
  {{- if .Values.clusterProxy.enabled }}
    clusterProxy:
      {{- omit .Values.clusterProxy "enabled" | toYaml | nindent 6 }}
  {{- end }}
