{{- $ns := (lookup "v1" "Namespace" "kube-system" "kube-system") -}}
{{- $clusterId := default (dig "metadata" "uid" "" ($ns)) "" -}}

apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ClusterClaim
metadata:
  name: id.k8s.io
spec:
  value: {{ required "A valid cluster id required!" $clusterId }}
