{{ if or .Values.clusterMetadata.store.secret.name .Values.clusterMetadata.store.clusterClaim.name }}

apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-info-generator
  namespace: open-cluster-management
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: klusterlet
      automountServiceAccountToken: true
      containers:
      - name: clusteradm
        image: ghcr.io/kluster-manager/clusteradm:{{ default .Chart.AppVersion .Values.bundleVersion.clusteradmImageVersion }}
        imagePullPolicy: Always
        args:
          - /clusteradm
          - get
          - cluster-info
          - --cluster-name={{ .Values.clusterMetadata.name }}
          {{ if .Values.clusterMetadata.store.secret.name }}
          - --store-in-configmap={{ default .Release.Namespace .Values.clusterMetadata.store.secret.namespace }}/{{ .Values.clusterMetadata.store.secret.name }}
          {{ end }}
          {{ with .Values.clusterMetadata.store.clusterClaim.name }}
          - --store-in-clusterclaim={{ . }}
          {{ end }}
      restartPolicy: Never
{{ end }}
