{{ if or .Values.clusterMetadata.store.secret.name .Values.clusterMetadata.store.clusterClaim.name }}

apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-info-generator
  namespace: open-cluster-management
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: klusterlet
      automountServiceAccountToken: true
      containers:
      - name: clusteradm
        image: {{ .Values.clusteradm.image }}:{{ default .Chart.AppVersion .Values.bundleVersion.clusteradmImageVersion }}
        imagePullPolicy: Always
        args:
          - /clusteradm
          - get
          - cluster-info
          - --cluster-name={{ .Values.clusterMetadata.name }}
          {{- if .Values.clusterMetadata.store.secret.name }}
          - --store-in-configmap={{ default .Release.Namespace .Values.clusterMetadata.store.secret.namespace }}/{{ .Values.clusterMetadata.store.secret.name }}
          - --create-namespace
          {{- end }}
          {{- with .Values.clusterMetadata.store.clusterClaim.name }}
          - --store-in-clusterclaim={{ . }}
          {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Never
{{ end }}
