apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-info-generator
  namespace: open-cluster-management
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: klusterlet
      automountServiceAccountToken: true
      containers:
      - name: clusteradm
        image: ghcr.io/kluster-manager/clusteradm:{{ default .Chart.AppVersion .Values.bundleVersion.clusteradmImageVersion }}
        imagePullPolicy: Always
        args:
          - /clusteradm
          - get
          - cluster-info
          - --cluster-name={{ .Values.clusterMetadata.name }}
          - --store-in-configmap={{ default .Release.Namespace .Values.secret.namespace }}/{{ .Values.secret.name }}
      restartPolicy: Never
