# Image of the managed service-account instances
image: quay.io/open-cluster-management/managed-serviceaccount
tag:

# Number of replicas
replicas: 1

featureGates:
  ephemeralIdentity: false

agentImagePullSecret: ""

# required for multicluster controlplane
kubeconfigSecretName: ""

kubectl:
  image: ghcr.io/appscode/kubectl-nonroot:1.25
