kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-auth-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: cluster-auth-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-auth-manager
  template:
    metadata:
      labels:
        app: cluster-auth-manager
    spec:
      {{- if .Values.kubeconfigSecretName }}
      automountServiceAccountToken: false
      {{- else }}
      serviceAccount: cluster-auth-manager
      automountServiceAccountToken: true
      {{- end }}
      containers:
        - name: manager
          image: {{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          args:
            - manager
            {{- if .Values.kubeconfigSecretName }}
            - --kubeconfig=/var/run/secrets/ocm/auth/kubeconfig
            {{- end }}
            - --registryFQDN={{ .Values.registryFQDN }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NAMESPACE
              value: {{ include "cluster-auth-manager.namespace" . }}
          volumeMounts:
          {{- if .Values.kubeconfigSecretName }}
            - mountPath: /var/run/secrets/ocm/auth
              name: ocm-auth
          {{- end }}
      volumes:
        {{- if .Values.kubeconfigSecretName }}
        - name: ocm-auth
          secret:
            defaultMode: 420
            secretName: {{ .Values.kubeconfigSecretName }}
        {{- end }}
