apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443