apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:extension-apiserver-authentication-reader:cluster-gateway
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: cluster-gateway
    namespace: {{ .Release.Namespace }}