apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-gateway-secret-reader
  namespace: {{ .Values.secretNamespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "*"
