apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-proxy-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      open-cluster-management.io/addon: cluster-proxy
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: cluster-proxy
    spec:
      serviceAccount: cluster-proxy-manager
      automountServiceAccountToken: true
      containers:
        - name: manager
          image: {{ .Values.registry }}/{{ .Values.image }}:{{ default .Chart.AppVersion .Values.tag }}
          imagePullPolicy: Always
          command:
            - /manager
          args:
            {{- if gt (int .Values.replicas) 1 }}
            - --leader-elect=true
            {{- end }}
            - --signer-secret-namespace={{ .Release.Namespace }}
            {{- if .Values.kubeconfigSecretName }}
            - --multicluster-kubeconfig=/var/run/secrets/ocm/auth/kubeconfig
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          volumeMounts:
          {{- if .Values.kubeconfigSecretName }}
            - mountPath: /var/run/secrets/ocm/auth
              name: ocm-auth
          {{- end }}
      volumes:
        {{- if .Values.kubeconfigSecretName }}
        - name: ocm-auth
          secret:
            defaultMode: 420
            secretName: {{ .Values.kubeconfigSecretName }}
        {{- end }}
