apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: fluxcd-addon
  annotations:
    addon.open-cluster-management.io/lifecycle: "addon-manager"
spec:
  addOnMeta:
    displayName: {{ .Chart.Name }}
    description: {{ .Chart.Description }}
  installStrategy:
    type: Placements
    placements:
      - name: global
        namespace: fluxcd-addon
  supportedConfigs:
    - group: fluxcd.open-cluster-management.io
      resource: fluxcdconfigs
      defaultConfig:
        name: fluxcd-config
        namespace: fluxcd-addon
