apiVersion: v2
name: cluster-manager-hub
description: A Helm chart for Open Cluster Manager Hub
type: application
version: v2024.2.25
appVersion: "v0.12.0"
home: https://open-cluster-management.io
sources:
- https://github.com/kluster-manager/installer
maintainers:
- name: appscode
  email: support@appscode.com
