properties:
  addonFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
  autoApprove:
    type: boolean
  bundleVersion:
    properties:
      addonManagerImageVersion:
        type: string
      operatorImageVersion:
        type: string
      placementImageVersion:
        type: string
      registrationImageVersion:
        type: string
      workImageVersion:
        type: string
    type: object
  hub:
    properties:
      registry:
        type: string
      tokenID:
        type: string
      tokenSecret:
        type: string
      useBootstrapToken:
        type: boolean
    type: object
  registrationFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
  workFeatures:
    items:
      properties:
        feature:
          type: string
        mode:
          default: Disable
          enum:
          - Enable
          - Disable
          type: string
      required:
      - feature
      type: object
    type: array
type: object
