hub:
  useBootstrapToken: false
  # randAlpha 6
  tokenID: ""
  # randAlpha 16
  tokenSecret: ""
  registry: quay.io/open-cluster-management

bundleVersion:
  registrationImageVersion: ""
  placementImageVersion: ""
  workImageVersion: ""
  operatorImageVersion: ""
  addonManagerImageVersion: ""

autoApprove: false

registrationFeatures: # +doc-gen:break
- feature: DefaultClusterSet
  mode: Enable

workFeatures: # +doc-gen:break
- feature: ManifestWorkReplicaSet
  mode: Enable

addonFeatures: # +doc-gen:break
- feature: AddonManagement
  mode: Enable
